Readme + cleanup for umi_hello example
zeroasiccorp/logik pull request #81
Opened 2024-04-02 22:41 UTC by sgherbst

2024-04-02 23:43 UTC, petergrossmann21 requested changes
While you are in here, can you add umi_hello to the CI suite?  This will be good for keeping it fresh.

Everything else looks ready to go

2024-04-02 23:59 UTC, sgherbst commented
@petergrossmann21 good idea - just added that

2024-04-03 00:38 UTC, sgherbst commented
noticed a typo in the new test file name - just fixed it

2024-04-03 02:14 UTC, petergrossmann21 approved these changes

2024-04-03 02:34 UTC, merged